project_id = "hmzqfcooxqucytxwljhg"

[functions.stripe-criar-assinatura]
verify_jwt = false

[functions.stripe-criar-cliente]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false




[functions.enviar-notificacao-vencimento]
verify_jwt = false

[cron.process-recurring-billing]
schedule = "0 0 1 * *" # Meia-noite do dia 1 de cada mês

[cron.notificar-vencimento]
schedule = "0 9 * * *" # Todo dia às 09:00

[cron.liberar-saldo-bloqueado]
schedule = "0 0 * * *" # Todo dia à meia-noite

