project_id = "hmzqfcooxqucytxwljhg"

[functions.stripe-criar-assinatura]
verify_jwt = false

[functions.stripe-criar-cliente]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false




[functions.enviar-notificacao-vencimento]
verify_jwt = false

[cron.process-recurring-billing]
schedule = "0 0 1 * *" # Meia-noite do dia 1 de cada mês

[functions.disparar-notificacoes-dia]
verify_jwt = false

[cron.notificar-vencimento]
schedule = "0 11 * * *" # Todo dia às 11:00 UTC (08:00 Brasília)


[cron.liberar-saldo-bloqueado]
schedule = "0 0 * * *" # Todo dia à meia-noite

