project_id = "hmzqfcooxqucytxwljhg"

[functions.stripe-criar-assinatura]
verify_jwt = false

[functions.stripe-criar-cliente]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
[functions.stripe-cancelar-assinatura]
verify_jwt = false




[functions.enviar-notificacao-vencimento]
verify_jwt = false


[functions.disparar-notificacoes-dia]
verify_jwt = false



[cron.liberar-saldo-bloqueado]
schedule = "0 0 * * *" # Todo dia à meia-noite

